---
title: "Boletin Fiscal do RN"
author: "NEAQ"
date: "20/05/2022"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r importacao_pacotes,echo=F,warning=F,message=F}
library(readxl)
library(dplyr)
library(tidyr)
library(zoo)
library(ggplot2)
library(scales)
library(lubridate)
library(ggThemeAssist)
library(formattable)
library(reactable)
library(esquisse)
library(reactablefmtr)
```

```{r importacao_base,echo=F,warning=F,message=F}
sigdef <- read_excel("20220406_sigdef.xls", 
                               sheet = "arrecadacao")
```

## Boletim Fiscal do Rio Grande do norte

```{r tratamento da base,echo=F,warning=F,message=F}
sigdef %>% 
  select(-id_uf, -co_periodo) %>% 
  filter(ESTADO == "Rio Grande do Norte") %>% 
  mutate(Período = as.yearmon(paste(ANO, MÊS, sep= "-"))) %>% 
  select(ESTADO,Período, 
         -(ANO:MÊS),
         `1.1 - PRIMÁRIO`:`TOTAL GERAL DA RECEITA TRIBUTÁRIA`) %>% 
  filter(Período > "dez 1999") %>% 
  mutate(ITCD2 = ITCD,
         IPVA2 = IPVA) %>% 
  mutate(IPVA = case_when(Período =="mar 2018" ~ ITCD2,
                          T ~ IPVA),
         ITCD = case_when(Período =="mar 2018" ~ IPVA2,
                          T ~ ITCD)) %>% 
  select(-ITCD2, -IPVA2) %>% 
  select(ESTADO,
         Período,
         `TOTAL DA ARRECADAÇÃO DO ICMS`,
         ITCD,
         IPVA,
         OUTROS,
         `TOTAL GERAL DA RECEITA TRIBUTÁRIA`) %>%
  rename(ICMS = `TOTAL DA ARRECADAÇÃO DO ICMS`) %>%
  tidyr::pivot_longer(cols = c(ICMS, IPVA, ITCD, OUTROS,
                        `TOTAL GERAL DA RECEITA TRIBUTÁRIA`),
               names_to = "Tributos",
               values_to = "Montante") %>% 
  arrange(Período, desc(Montante)) %>% 
  mutate(Tributos = factor(Tributos,
                           levels = c("TOTAL GERAL DA RECEITA TRIBUTÁRIA",
                                      "ICMS",
                                      "IPVA",
                                      "ITCD",
                                      "OUTROS")))-> Impostos_Totais
```


```{r helper_ggplot,echo=F,warning=F,message=F}
StyleTheme <-  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        axis.title.x  = element_blank(),
        legend.box      = "horizontal",
        legend.position = "bottom",
        axis.text.x = element_text(size = 8, color = "Black"),
        axis.text.y = element_text(size = 8, color = "black")) 
```


### Conteúdo 1

```{r grafico_arrecadacao,fig.align="center",echo=F,warning=F,message=F}
Impostos_Totais %>%
  ggplot(.,aes(x= Período, y = Montante, color= Tributos)) +
  geom_line(size = 1.1) +
  scale_y_continuous(labels = comma_format(big.mark = ".",
                                           decimal.mark = ",")) +
  StyleTheme +
  labs(title = "Arrecadação de Impostos do RN e Suas Evoluções (1997 - 2022)",
       subtitle = "(Valores Nominais)",
       caption = "Observatório Conjuntura Econômica do RN \n NEAQ-DEPEC/UFRN \n Fonte: Confaz (2022)", 
       position = c("left", "top"))+
  scale_colour_manual(values = c("#32373b", "#62b851",
                                 "#009fb7", "#b20d30",
                                 "#f4b942"))
```

### Conteúdo 2

```{r tabela_impostos,echo=F,warning=F,message=F}
Impostos_Totais %>%
  filter(Período > "dez 2014") %>%
  mutate(Ano = year(Período)) %>%
  pivot_wider(names_from = Tributos, values_from = Montante) %>% 
  group_by(Ano) %>%
  summarise(ICMS = sum(ICMS),
            IPVA = sum(IPVA),
            ITCD= sum(ITCD),
            OUTROS = sum(OUTROS),
            Total = sum(`TOTAL GERAL DA RECEITA TRIBUTÁRIA`)) %>% 
  pivot_longer(-c(Total, Ano),
               names_to = "Tributos",
               values_to = "Montante") %>% 
  mutate(prop = (Montante/Total)) %>%
  select(-c(Montante, Total)) %>% 
  pivot_wider(names_from = Tributos, values_from = prop)  %>% 
  reactable(defaultColDef = colDef(headerClass = "header", align = "center",
                                   headerStyle = list(
                                     background = "#7290ba",
                                     color  = "#f5f5f5")),
            columns = list(
              Ano = colDef(align = "left"),
              ICMS = colDef(cell = data_bars(., 
                                             number_fmt = formattable::percent,
                                             text_position = "outside-base",
                                             force_outside = c(0,0.4),
                                             fill_color = "#7290ba")),
              IPVA = colDef(cell = data_bars(.,
                                             number_fmt = formattable::percent,
                                             text_position = "outside-base",
                                             force_outside = c(0,0.4),
                                             fill_color = "#7290ba")),
              ITCD = colDef(cell = data_bars(.,
                                             number_fmt = formattable::percent,
                                             text_position = "outside-base",
                                             force_outside = c(0,0.4),
                                             fill_color = "#7290ba")),
              OUTROS = colDef(cell = data_bars(., 
                                               number_fmt = formattable::percent,
                                               text_position = "outside-base",
                                               force_outside = c(0,0.4),
                                               fill_color = "#7290ba"))),
            bordered = T,
            striped = T) %>% 
  google_font("Roboto")
```

### Conteúdo 3

```{r icms_setor,fig.align="center",echo=F,warning=F,message=F}
sigdef %>% 
  mutate(Período = as.yearmon(paste(ANO, MÊS, sep= "-"))) %>% 
  filter(Período > "dez 2020") %>% 
  select(Período:`1.3 - TERCIÁRIO`, `TOTAL DA ARRECADAÇÃO DO ICMS`) -> SetoresI

SetoresI %>% 
  pivot_longer(cols = -c(Período, `TOTAL DA ARRECADAÇÃO DO ICMS`), 
               names_to = "Setores",
               values_to = "Montante") %>% 
  mutate(Setores = substring(Setores, first = 7)) %>% 
  ggplot(aes(Período, Montante, fill = Setores)) +
  geom_col(position = "stack") +
  StyleTheme +
  scale_y_continuous(labels = comma_format(big.mark = ".",
                                           decimal.mark = ",")) +
  ggtitle("Valor arrecadado do ICMS por setores")
```


### Conteúdo 4

```{r var_icms,fig.align="center",echo=F,warning=F,message=F}
pervar <- function(x) { #função de variação percentual tem que desaparecer, dá pra fazer tudo dentro dos pipes
  (x - lag(x))/lag(x)
}

sigdef %>% 
  mutate(Período = as.yearmon(paste(ANO, MÊS, sep= "-"))) %>%
  select(ESTADO,
         Período,
         `TOTAL DA ARRECADAÇÃO DO ICMS`,
         IPVA,
         ITCD,
         `TOTAL GERAL DA RECEITA TRIBUTÁRIA`) %>%
  rename(ICMS = `TOTAL DA ARRECADAÇÃO DO ICMS`) %>%
  filter(Período > "dez 2018") %>%
  mutate(Período = as.yearqtr(Período, format = "%y Q%q")) %>%
  group_by(Período) %>%
  summarise(across(everything()[-1], sum)) %>%
  mutate(across(ICMS:`TOTAL GERAL DA RECEITA TRIBUTÁRIA`, ~ .x/.x[1])) %>%
  pivot_longer(cols = ICMS:`TOTAL GERAL DA RECEITA TRIBUTÁRIA`,
               names_to = "Tributos", values_to = "Montante") %>%
  mutate(Tributos = factor(Tributos,
                           levels = c("TOTAL GERAL DA RECEITA TRIBUTÁRIA",
                                      "ICMS",
                                      "IPVA",
                                      "ITCD",
                                      "OUTROS"))) -> num_indice_arrecadacao

ggplot(num_indice_arrecadacao, aes(x = Período,y = Montante, fill = Tributos, label = percent(Montante))) +
  geom_bar(stat = "identity", position = "dodge") +
  StyleTheme +
  theme(axis.text.x = element_text(angle = 22.5)) +
  scale_x_yearqtr(format = "%YQ%q") +
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey") +
  scale_fill_manual(values = c("#32373b",
                               "#62b851",
                               "#009fb7", "#b20d30",
                               "#f4b942")) +
  scale_y_continuous(labels = scales::percent) +
  annotate("text", x = 2021.92, y = 1.5,
           label = "24.13%", angle = 90,
           hjust = 0.4, vjust = 0.2,
           fontface = "bold", size = 3.7) +
  annotate("text", x = 2022, y = 1.5,
           label = "15.74%", angle = 90,
           hjust = 0.4, vjust = -0.4,
           fontface = "bold",size = 3.7) +
  annotate("text", x = 2022, y = 1.5,
           label = "48.41%", angle = 90,
           vjust = 1, hjust = 0.4,
           fontface = "bold",size = 3.7) +
  annotate("text", x = 2022.06, y = 1.5,
           label = "23.79%", angle = 90,
           vjust = 1, hjust = -.07,
           fontface = "bold",size = 3.7) +
  labs(y = "Variação Percentual",
       title = "Variação Percentual dos Tributos do RN (2019 - 2022)",
       caption = "Observatório Conjuntura Econômica do RN \n NEAQ-DEPEC/UFRN \n Fonte: Confaz (2022)", position = c("left", "top"))
```

  
  
  
  